# Generated by Django 4.1.2 on 2022-11-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='band',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='type',
        ),
        migrations.AlterField(
            model_name='band',
            name='year_formed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.IntegerField(),
        ),
    ]
